# The name of this app. Must be unique within a project.
name: app

type: 'php:8.4'

runtime:
    extensions:
        - mongodb


web:
  locations:
    "/":
      root: "public"
      expires: 1h
      passthru: "/index.php"


mounts:
  "/var/cache": { source: local, source_path: var/cache }

disk: 256

relationships:
    mariadb: 'mariadb:mysql'
    mongodb: 'mongodb:mongodb'

hooks:
  build: |
    set -x -e

    curl -s https://get.symfony.com/cloud/configurator | bash

    symfony-build
  deploy: |
    set -x -e

    symfony-deploy
