version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
  
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "8090:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: thomas
      MONGO_INITDB_ROOT_PASSWORD: japan
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local